### ISSUE TITLE
unselect-channels warning message

### ISSUE THREAD

**Issue by fabienBourban** [mmlabs-mindmaze/eegview#3]
When you define a channel to unselect then you will get a warning if the wanted channel is not present in a given pannel. The warning is generic as this:
`20/04/20 09:58:30 WARN  eegview          : channel chan1 does not exist`

if possible you should at least precise in wich panel the warning was raised, like:
`20/04/20 09:58:30 WARN  eegview          : channel chan1 does not exist in panel XXX`

**Comment by nbourdau** [comment]
PR open at https://review.gerrithub.io/c/mmlabs-mindmaze/eegview/+/490701
Waiting for review
